import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Link from "next/link"
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="navbar">
          
          {/* <div className="navbar-logo">
            <img src="/logo.png" alt="Logo" className="logo" />
          </div> */}

          <nav className="navbar-menu">
            <Link href="/">About</Link>
            <Link href="/list">Blog</Link>
            <Link href="/words">...</Link>
            <Link href="/write">write</Link>
          </nav>

          {/* 우측 아이콘들 */}
          {/* <div className="navbar-right">
            <button className="icon-button" aria-label="Search">
              🔍
            </button>
            <button className="login-button">Login</button>
          </div> */}

        </header>
        {children}
      </body>
    </html>
  );
}
